apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: java-spring-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-spring-api
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
