apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: java-spring-api-rules
  labels:
    prometheus: sybrenbolandit
    role: alert-rules
spec:
  groups:
  - name: java-spring-api
    rules:
      - alert: NoHealthyHosts
        expr: sum(up{job="java-spring-api"}) < 1 or absent(up{job="java-spring-api"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "No healthy hosts - java-spring-api"
