apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-spring-api
  labels:
    prometheus: sybrenbolandit
spec:
  selector:
    matchLabels:
      app: java-spring-api
  endpoints:
  - port: actuator
    path: /actuator/prometheus
  targetLabels:
  - env
  - app
