apiVersion: v1
kind: Service
metadata:
  name: java-spring-api
  labels:
    app: java-spring-api
spec:
  selector:
    app: java-spring-api
  ports:
  - name: web
    port: 8080
  - name: actuator
    port: 8081
